//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace rstemenu {
    
    
    public partial class Lower_Crowding_Mixed {
        
        /// <summary>
        /// crowding_lower_right_1_s0 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RadioButton crowding_lower_right_1_s0;
        
        /// <summary>
        /// crowding_lower_right_1_s5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RadioButton crowding_lower_right_1_s5;
        
        /// <summary>
        /// crowding_lower_right_2_s0 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RadioButton crowding_lower_right_2_s0;
        
        /// <summary>
        /// crowding_lower_right_2_s1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RadioButton crowding_lower_right_2_s1;
        
        /// <summary>
        /// crowding_lower_right_2_s2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RadioButton crowding_lower_right_2_s2;
        
        /// <summary>
        /// crowding_lower_right_2_s3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RadioButton crowding_lower_right_2_s3;
        
        /// <summary>
        /// crowding_lower_right_2_s4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RadioButton crowding_lower_right_2_s4;
        
        /// <summary>
        /// crowding_lower_right_2_s5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RadioButton crowding_lower_right_2_s5;
        
        /// <summary>
        /// crowding_lower_right_3_s0 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RadioButton crowding_lower_right_3_s0;
        
        /// <summary>
        /// crowding_lower_right_3_s1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RadioButton crowding_lower_right_3_s1;
        
        /// <summary>
        /// crowding_lower_right_3_s2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RadioButton crowding_lower_right_3_s2;
        
        /// <summary>
        /// crowding_lower_right_3_s3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RadioButton crowding_lower_right_3_s3;
        
        /// <summary>
        /// crowding_lower_right_3_s4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RadioButton crowding_lower_right_3_s4;
        
        /// <summary>
        /// crowding_lower_right_3_s5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RadioButton crowding_lower_right_3_s5;
        
        /// <summary>
        /// crowding_lower_left_1_s0 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RadioButton crowding_lower_left_1_s0;
        
        /// <summary>
        /// crowding_lower_left_1_s1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RadioButton crowding_lower_left_1_s1;
        
        /// <summary>
        /// crowding_lower_left_1_s2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RadioButton crowding_lower_left_1_s2;
        
        /// <summary>
        /// crowding_lower_left_1_s3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RadioButton crowding_lower_left_1_s3;
        
        /// <summary>
        /// crowding_lower_left_1_s4 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RadioButton crowding_lower_left_1_s4;
        
        /// <summary>
        /// crowding_lower_left_1_s5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RadioButton crowding_lower_left_1_s5;
        
        /// <summary>
        /// crowding_lower_left_2_s0 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RadioButton crowding_lower_left_2_s0;
        
        /// <summary>
        /// crowding_lower_left_2_s5 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.RadioButton crowding_lower_left_2_s5;
        
        /// <summary>
        /// showing_error control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label showing_error;
        
        /// <summary>
        /// submit_lower_right control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Button submit_lower_right;
    }
}
